
/*
CREATING ROLES AND ASSIGNING THE REQUIRED PRIVILIGES
*/
set serveroutput on;
DECLARE
   v_count INTEGER;
BEGIN
   SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'PASSENGERUSER';
   IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER PassengerUser IDENTIFIED BY WorldWideTraveller2024';    
        DBMS_OUTPUT.PUT_LINE('User PASSENGER CREATED and assigned the necessary priviliges SUCCESSFULLY');
   ELSE
        DBMS_OUTPUT.PUT_LINE('User already exists');
   END IF;
END;
/
GRANT CREATE SESSION TO PassengerUser;
GRANT EXECUTE ON PASSENGER_ONBOARDING_PKG TO PASSENGERUSER;
GRANT EXECUTE ON PASSENGER_UPDATING_PKG TO PASSENGERUSER;
GRANT EXECUTE ON PASSENGER_DELETE_PKG TO PASSENGERUSER;    
GRANT EXECUTE ON ORDER_DELETE_PKG TO PASSENGERUSER;

DECLARE
   v_count INTEGER;
BEGIN
   SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'ACCOUNTANT';
   IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER ACCOUNTANT IDENTIFIED BY BookKeepingMoneyMan2024';
        DBMS_OUTPUT.PUT_LINE('User ACCOUNTANT CREATED and assigned the necessary priviliges');
   ELSE
        DBMS_OUTPUT.PUT_LINE('User already exists');
   END IF;
END;
/

GRANT CREATE SESSION TO ACCOUNTANT;
GRANT EXECUTE ON acct_pkg TO ACCOUNTANT;
GRANT SELECT ON  BAGGAGE TO ACCOUNTANT;
GRANT SELECT ON  ORDERS TO ACCOUNTANT;
GRANT SELECT ON  FLIGHT TO ACCOUNTANT;
GRANT SELECT ON  TICKET TO ACCOUNTANT;
GRANT SELECT ON  AIRLINES TO ACCOUNTANT;
GRANT CREATE VIEW TO ACCOUNTANT;

DECLARE
   v_count INTEGER;
BEGIN
   SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'ANALYST';
   IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER ANALYST IDENTIFIED BY BigDataScientist2024';

        DBMS_OUTPUT.PUT_LINE('User ACCOUNTANT CREATED and assigned the necessary priviliges');
   ELSE
        DBMS_OUTPUT.PUT_LINE('User already exists');
   END IF;
END;
/

GRANT CREATE SESSION TO ANALYST;
GRANT SELECT ON  BAGGAGE TO ANALYST;
GRANT SELECT ON  ORDERS TO ANALYST;
GRANT SELECT ON  FLIGHT TO ANALYST;
GRANT SELECT ON  TICKET TO ANALYST;
GRANT SELECT ON  AIRLINES TO ANALYST;
GRANT SELECT ON  SCHEDULE TO ANALYST;
GRANT SELECT ON  TERMINAL TO ANALYST;
GRANT SELECT ON  AIRPORT TO ANALYST;
GRANT SELECT ON  AIRLINE_STAFF TO ANALYST;       
GRANT CREATE VIEW TO ANALYST;

DECLARE
   v_count INTEGER;
BEGIN
   SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'AIRLINESTAFF';
   IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER AirlineStaff IDENTIFIED BY GroundWorkingMan2024';
          
        DBMS_OUTPUT.PUT_LINE('User AIRLINESTAFF CREATED and assigned the necessary priviliges SUCCESSFULLY');
   ELSE
        DBMS_OUTPUT.PUT_LINE('User already exists');
   END IF;
END;
/

GRANT CREATE SESSION TO AirlineStaff;
GRANT EXECUTE ON ONBOARD_TICKET_PKG TO AIRLINESTAFF;
GRANT EXECUTE ON ticket_updating_pkg TO AIRLINESTAFF;
GRANT EXECUTE ON PASSENGER_ONBOARDING_PKG TO AIRLINESTAFF;
GRANT EXECUTE ON passenger_delete_pkg TO AIRLINESTAFF;
GRANT EXECUTE ON ONBOARD_FLIGHT_PKG TO AIRLINESTAFF;
GRANT EXECUTE ON ORDER_DELETE_PKG TO AIRLINESTAFF;
GRANT EXECUTE ON FLIGHT_DELETE_PKG TO AIRLINESTAFF;
GRANT EXECUTE ON UPDATE_TICKET_PKG TO AIRLINESTAFF;   
GRANT SELECT ON FLIGHT TO AIRLINESTAFF; 
GRANT SELECT ON SCHEDULE TO AIRLINESTAFF;         
GRANT SELECT ON TICKET TO AIRLINESTAFF;       
GRANT SELECT ON BAGGAGE TO AIRLINESTAFF;    
GRANT SELECT ON ORDERS TO AIRLINESTAFF;    